use crate::solver::Solvers;

pub struct Edition {
    pub day01: Option<Solvers>,
    pub day02: Option<Solvers>,
    pub day03: Option<Solvers>,
    pub day04: Option<Solvers>,
    pub day05: Option<Solvers>,
    pub day06: Option<Solvers>,
    pub day07: Option<Solvers>,
    pub day08: Option<Solvers>,
    pub day09: Option<Solvers>,
    pub day10: Option<Solvers>,
    pub day11: Option<Solvers>,
    pub day12: Option<Solvers>,
    pub day13: Option<Solvers>,
    pub day14: Option<Solvers>,
    pub day15: Option<Solvers>,
    pub day16: Option<Solvers>,
    pub day17: Option<Solvers>,
    pub day18: Option<Solvers>,
    pub day19: Option<Solvers>,
    pub day20: Option<Solvers>,
    pub day21: Option<Solvers>,
    pub day22: Option<Solvers>,
    pub day23: Option<Solvers>,
    pub day24: Option<Solvers>,
    pub day25: Option<Solvers>,
    pub day26: Option<Solvers>,
    pub day27: Option<Solvers>,
    pub day28: Option<Solvers>,
    pub day29: Option<Solvers>,
    pub day30: Option<Solvers>,
    pub day31: Option<Solvers>,
}
